name: "Automatic requirement.txt for Python Projects"
description: "This action will automatically create the requirement.txt file for a python project using the pipreqs tool."
author: "Ryan Rozario"

inputs:
  PROJECT_PATH:
    description: "Gives the path of the project"
    required: true
    default: "."

  REQUIREMENT_PATH:
    description: "Folder where requirement.txt has to be saved in"
    required: true
    default: "requirement.txt"


runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: 'code'
  color: 'yellow'
