name: "pipreqs github action"
description: "pipreqs allows you to generate the requirement.txt file based on the imports of the project. This action will allow you to automatically create the requirement.txt file when you pull or push"
author: "Ryan Rozario"

inputs:
  PROJECT_PATH:
    description: "Gives the path of the project"
    required: true
    default: "."

  REQUIREMENT_PATH:
    description: "Folder where requirement.txt has to be saved in"
    required: true
    default: "requirement.txt"


runs:
  using: "docker"
  image: "Dockerfile"
